---
- name: print os info
  hosts: localhost
  gather_facts: False
  tasks:
    - name: "facts"
      setup:
      register: output
    - name: "print output"
      debug:
         msg: "{{output}}"

    - name: "print output 2"
      debug:
       msg: |
                   ansible_distribution: {{ ansible_os_family }}
                   ansible_distribution: {{ ansible_distribution }}
                   ansible_distribution_version: {{ ansible_distribution_version }}
                   ansible_distribution_major_version: {{ ansible_distribution_major_version }}
                   ansible_distribution_release: {{ ansible_distribution_release }}                                                                                   